// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzjslwqdvkdqhqvdpjqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6anNsd3FkdmtkcWhxdmRwanFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1ODc2NjQsImV4cCI6MjA1OTE2MzY2NH0.q28lswW9bu1OtHH_vqY-GgcvT_--yRb_NABuWoS_otU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);